### ISSUE TITLE
Erreur avec la commande wget

### ISSUE THREAD

**Issue by LexisDG** [IFT2245/NameValidator#4]
La commande spécifiée dans le README
"wget https://github.com/SamuelYvon/NameValidator/blob/master/validate.py" 
télécharge la page web html et non le fichier validate.py uniquement

**Comment by SamuelYvon** [comment]
Oui, merci. C'est parce que j'ai déplacé le projet de mon compte vers une organisation pour le cours. Je vais régler ça dans les prochaines minutes.

**Comment by SamuelYvon** [comment]
Réglé.

La raison que j'ai mentionné est pas bonne; j'avais mal réparé le lien.
