### ISSUE TITLE
Erreur de version

### ISSUE THREAD

**Issue by LexisDG** [IFT2245/NameValidator#5]
Lorsque j'essaie avec la dernière version (1.4 selon le code) avec le dernier commit étant 
"Update download link ", j'obtiens le message suivant:
_Erreur en exécutant le script! Veuillez ouvrir un bug sur github!
Le script n'est pas à jour. Veuillez le mettre à jour avec la dernière version en ligne._
Je suis sur MacOS et j'ai aussi testé sur ma VM Ubuntu.

**Comment by SamuelYvon** [comment]
Merci! C'est fixé.
